ALTER TABLE kpi_template_cycle
    MODIFY COLUMN status ENUM('DRAFT', 'ACTIVE', 'PENDING_APPROVAL', 'CLOSING', 'DEACTIVATED', 'CLOSED') NOT NULL;

ALTER TABLE employee_kpi_forms
    MODIFY COLUMN status ENUM('ASSIGNED', 'IN_PROGRESS', 'FINALIZED', 'CLOSED', 'SENT_TO_EMPLOYEE', 'ACKNOWLEDGED') NOT NULL;
