spring.application.name=epms

server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/epms}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:genshinimpact1@}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMTIzNDU2Nzg5MDEyMzQ1Ng==
app.jwt.access-token-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:3600000}
app.jwt.refresh-token-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}